### ISSUE TITLE
Suggest renaming`interpolate!`  to `fill!`

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#109]
My intuition for interpolate! is a function that can retrieve geoarray values between exact indices. For this reason I would suggest renaming `interpolate!` to `fill!`.

**Comment by evetion** [comment]
Hmm, `fill!` would be a better name, but it would be a breaking change. And this doesn't solve your implicit question, that you want a `interpolate` method that retrieves values by interpolation right? Would you have a preference, for the interpolation method?

**Comment by alex-s-gardner** [comment]
I'm not in need of an `interpolate` method yet but I can see this as a basic tool that would need to be included with `GeoArrays`. I think changing `interpolate!` to `fill!` earlier than later would cause the least disruption if you agree that it's a needed change.
