### ISSUE TITLE
return indices as CartesianIndex

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#115]
If `indices` were returned as `CartesianIndex` then they can be used to directly index info a `geoarray` when dealing with `Vector` of points

**Comment by alex-s-gardner** [comment]
This is what I'm doing now:

# find indices of points
ind = indices.(Ref(ga0), xy);
        
# extract values
ind = [CartesianIndex((ij[1], ij[2])) for ij in ind]
val = ga0[ind]

**Comment by evetion** [comment]
I think it's a fair point that we should accept and return CartesianIndices, although it would be breaking. Note you can rewrite your code to:

```julia
CartesianIndex.(Tuple.(indices.(Ref(ga), xy)))
```

And you can actually index into the GeoArray directly with floating point numbers: `getindex.(Ref(ga), SVector{2}.(xy))`.

**Comment by evetion** [comment]
In GeoArrays 0.8, `indices(::GeoArray, x, y)` are now returned as `CartesianIndex`.
