### ISSUE TITLE
Type conversion 

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#119]
I'm finding that in my workflow I need to convert Int16 GeoArrays to Floa32 when applying some filters to the data. The only way I can figure to do this is to create an entirely new GeoArray. A `convert!` function would be helpful for myself and maybe others.

**Comment by evetion** [comment]
Closed by #121. You can now do `convert(GeoArray{Type}, ga)`. This isn't the proposed `convert!`, but there's no way to go from Int16 to Float32 without allocating something new.
