### ISSUE TITLE
`affine!` or `f!` funciton 

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#120]
For consistency with `crs!` I wonder if a `affine!` or `f!` should be added

**Comment by evetion** [comment]
There's bbox! Because I thought that's easier if you already have a raster with a known size. But we could easily add setting an affine transform with affine!.

**Comment by alex-s-gardner** [comment]
`affine!` is useful when creating GeoArrays that match arrays that have been read in ... something I often do... right now I just do

`ga1.f = ga2.f`

but it might make sense to also have `affine!` as there is a `crs!`

Any reason that `ga.f` is not `ga.affine`?
