### ISSUE TITLE
Should bbox return an Extent?

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#122]
Should all of the bbox named tuples be changed to Extents?

**Comment by evetion** [comment]
Yes it should, I should be eating my own dogfood.

**Comment by evetion** [comment]
I think Extent is an improvement over the namedtuple (especially since we're adopting it in multiple places), but I'm still unhappy with it in terms of naming (is it x, or X, or should it be longitude). And is the (min, max) thing also (west, east) etc.

**Comment by evetion** [comment]
In GeoArrays 0.8, `GeoInterface.extent(::Geoarray)` now returns an Extent.
