### ISSUE TITLE
add support of `coords` to return a `StepRangeLen`

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/GeoArrays.jl#125]
Could support be added to `coords` such that it returns a `StepRangeLen` for 'x' and 'y' coordinates?

StepRangeLen then be passed directly to Interpolations.jl

**Comment by evetion** [comment]
Do you have a code snippet for your use of Interpolations? We could add a pkg extension (Julia 1.9 only) for it. Or let the fill API also accept Interpolation options instead of just GeoStatsSolvers.

**Comment by evetion** [comment]
Also, stepranges could only work on non-rotated rasters, so it's difficult to support directly.

**Comment by alex-s-gardner** [comment]
Other aspects of `coords` also only non-rotated rasters, so I don't see that as an issue another than throwing an error... rotated rasters are pretty uncommon in my world 

```
  xy11 = ga.f((1,1));
  m, n = size(ga.A)[1:2];
  dx = ga.f.linear[1,1];
  dy = ga.f.linear[2,2];
  x0 = xy11[1]:dx:(xy11[1] + dx*(m-1));
  y0 = xy11[2]:dy:(xy11[2] + dy*(n-1));
        
 itp = extrapolate(scale(interpolate(ga.A[:,:,1], BSpline(interp)), x0, y0 ), nodatavalue)
 val = itp.(x, y)
```

**Comment by evetion** [comment]
I've added `ranges`:

```julia
julia> ga = GeoArray(rand(10, 10))
10x10x1 Array{Float64, 3} with AffineMap([1.0 0.0; 0.0 1.0], [0.0, 0.0]) and undefined CRS

julia> x0, y0 = GeoArrays.ranges(ga)
(0.5:1.0:9.5, 0.5:1.0:9.5)
```
