### ISSUE TITLE
Make dims a type parameter

### ISSUE THREAD

**Issue by mauro3** [evetion/GeoArrays.jl#34]
Why not have the dimensions as a type parameter?  That is what AbstractArrays usually have.
```julia
mutable struct GeoArray{T<:Union{Real, Union{Missing, Real}}, N} <: AbstractArray{T, N}
    A::AbstractArray{T, N}
    f::AffineMap
    crs::AbstractString
end
```
(and why is it a "mutable" struct?)

**Comment by mauro3** [comment]
Ok, I was kinda confused.  The third dimension is not for z-coordinate but for different bands, right?  

If so, the GeoArray is more akin to several 2-D arrays, one for each band.  Maybe in that case an interface like so would be better: get 4th band `ga[4]`, index i,j of n-th band: `ga[n],[i,j]`?

**Comment by evetion** [comment]
Yeah, the dimensions are x, y, bands. The x, y dimensions are special/spatial, handled by the stored AffineMap.

The ordering is hard to change without breaking current uses. But you can already do `ga[i, j]` which automatically appends and becomes `ga[i, j, :]`. I will try to clarify this in the `README.md`.

I'm now also looking into labeling/metadata of bands, so things like `(:r, :g, :b)` or `( :z)` also become clearer. Maybe we can then do `ga[:z]` or `ga[i, j, :z]`.

The mutable thing is a preference, I'd like to "edit" large `GeoArray`s, without having to duplicate them.

**Comment by evetion** [comment]
Clarified the dimensions in https://github.com/evetion/GeoArrays.jl/commit/69abf10dea266675f2615cade9d3f0e53c752f45. Let me know if this would've helped for you.

**Comment by mauro3** [comment]
Yes, that certainly helps.

However, I do feel that it's rather a collection of 2D arrays sharing the same "grid", than a 3D array.  So, yep, something to ponder.
