### ISSUE TITLE
Allow ranges in getindex

### ISSUE THREAD

**Issue by maxfreu** [evetion/GeoArrays.jl#49]
Hi! `geoarray[1,1]` works and returns the contents of all bands at position 1,1. However `ga[1:10,1:10]` errors. Therefore I propose to introduce:
```julia
Base.getindex(ga::GeoArray, I::Vararg{<:AbstractRange, 2}) = getindex(ga.A, I..., :)
```
Edit: Actually I would boil down the whole rest to:
```julia
Base.getindex(ga::GeoArray, I) = getindex(ga.A, I)
```

**Comment by Dsantra92** [comment]
Can I work on it?

**Comment by evetion** [comment]
Feel free to do so, I welcome PRs. Note however, that it's probably not as easy as:
```julia
Base.getindex(ga::GeoArray, I) = getindex(ga.A, I)
```
As this wouldn't support `ga[1:10,1:10]`, because ga.A has three dimensions. I do think the first suggestion by @maxfreu would work.

Don't forget to add a test for it as well.

**Comment by Dsantra92** [comment]
@evetion  on it.
