### ISSUE TITLE
Read single band from raster

### ISSUE THREAD

**Issue by KrOstir** [evetion/GeoArrays.jl#72]
When working with large rasters, e.g. with satellite images that can be GB in size, it is useful to be able to read only one band (or a selection of them) to GeoArray. Now the best option is to read the whole dataset and subset by band.

As suggested by @visr ArchGDAL has the `ArchGDAL.getband()` that could be exported to GeoArrays. GeoArrays.jl could add a method `getband(::GeoArray, i::Int)::GeoArray` to enable reading by band.

See also the conversation at Julia Discourse: [GeoArrays band math](https://discourse.julialang.org/t/geoarrays-band-math/65947/1).

**Comment by evetion** [comment]
We use `getband` from `ArchGDAL` in the `read` function. I'd propose to extend it:

```julia
function read(fn::AbstractString; masked=true, band=1/"name"/nothing)
```
Would that satisfy your usecase?

**Comment by KrOstir** [comment]
> ```julia
> function read(fn::AbstractString; masked=true, band=1/"name"/nothing)
> ```

Yes, that would be perfect. `getband(dataset::AbstractDataset, i::Integer)` just has the integer for band number, and that can be used in the `read`. Default is to read all bands.

**Comment by evetion** [comment]
Btw, @KrOstir if you have memory issues, you can lazily load the dataset with `ga = read(fn::AbstractString; masked=false)` and only access the data that fits into memory, e.g. `ga[100:200,100:200,1]`.
