### ISSUE TITLE
BBox is Float or Int

### ISSUE THREAD

**Issue by KrOstir** [evetion/GeoArrays.jl#77]
Currently, BBox is defined as Float64.

```julia
bbox::NamedTuple{(:min_x, :min_y, :max_x, :max_y),Tuple{Float64, Float64, Float64, Float64}})
```

This is mostly true, but BBox can also be Int64. Or a combination of them (each element can be either Int or Float). `GeoArrays` does not handle this.

```julia
julia> GeoArrays.bbox_to_affine((10,10), (min_x=10, min_y=10, max_x=100, max_y=100))
ERROR: MethodError: no method matching bbox_to_affine(::Tuple{Int64, Int64}, ::NamedTuple{(:min_x, :min_y, :max_x, :max_y), NTuple{4, Int64}})
Closest candidates are:
  bbox_to_affine(::Tuple{Integer, Integer}, ::NamedTuple{(:min_x, :min_y, :max_x, :max_y), NTuple{4, Float64}})
```

**Comment by evetion** [comment]
Agreed, this also should be fixed for a lot of other methods in the codebase.

**Comment by KrOstir** [comment]
Is it necessary to specify type?

Of course, it is beneficial, but if someone would try bbox with string or something else, errors will happen somewhere else 😀.
