### ISSUE TITLE
compat for ArchGDAL to 0.8

### ISSUE THREAD

**Issue by kongdd** [evetion/GeoArrays.jl#92]
ArchGDAL v0.8 has been released. Whether it is possible compat for ArchGDAL 0.8?

**Comment by kongdd** [comment]
Dear Maarten, 

Another thing: 

Could I invite you have a review about the package [`Stars.jl`](https://github.com/jl-spatial/Stars.jl). 
Stars might use `GeoArrays` inappropriately in previous version. 
But now, most functions are moved , and are imported from `GeoArrays`, except for `st_plot.jl`, `st_read.jl`, and `st_write.jl`. 
This is mainly because I need to change some setting in those functions, while GeoArrays did not provide the interface. 

Thanks for your awesome package.

Regards,
Dongdong Kong

**Comment by evetion** [comment]
Fixed in latest release https://github.com/JuliaRegistries/General/pull/57409

**Comment by evetion** [comment]
> Could I invite you have a review about the package [`Stars.jl`](https://github.com/jl-spatial/Stars.jl). 
> Stars might use `GeoArrays` inappropriately in previous version. 
> But now, most functions are moved , and are imported from `GeoArrays`, except for `st_plot.jl`, `st_read.jl`, and `st_write.jl`. 
> This is mainly because I need to change some setting in those functions, while GeoArrays did not provide the interface. 

I'm not sure what there is to review. You're free to copy everything with attribution. Feel free to report issues with the interface here.

**Comment by kongdd** [comment]
Thank you.
